'use client';

/**
 * CustomRoleInput - Textarea for describing a custom SDLC role.
 *
 * Two-column layout:
 * - Left: Textarea with rich placeholder for custom role description.
 * - Right: "How Role Skills Work" examples panel showing 3 predefined role examples.
 *
 * T020: Custom role input view within the onboarding sub-flow.
 * Source: FR-002, US1
 */
import { observer } from 'mobx-react-lite';
import { ArrowLeft, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useRoleSkillStore } from '@/stores/RootStore';
import { CUSTOM_ROLE_EXAMPLES } from '../constants/skill-wizard-constants';

export interface CustomRoleInputProps {
  /** Called when user clicks "Back to grid". */
  onBack: () => void;
  /** Called when user clicks "Generate Skill". */
  onGenerate: () => void;
  /** Whether generation is in progress. */
  isGenerating?: boolean;
}

const MAX_CHARS = 5000;
const MIN_CHARS = 10;

export const CustomRoleInput = observer(function CustomRoleInput({
  onBack,
  onGenerate,
  isGenerating = false,
}: CustomRoleInputProps) {
  const roleSkillStore = useRoleSkillStore();
  const description = roleSkillStore.customRoleDescription;
  const charCount = description.length;
  const canGenerate = charCount >= MIN_CHARS && !isGenerating;

  return (
    <div className="flex flex-col gap-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Custom Role</h3>
        <button
          onClick={onBack}
          className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
          aria-label="Back to role grid"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to grid
        </button>
      </div>

      {/* Two-column layout */}
      <div className="flex flex-col md:flex-row gap-4">
        {/* Left panel — Form */}
        <div className="flex-[3] flex flex-col gap-3">
          <p className="text-sm text-muted-foreground">
            Describe your role, responsibilities, and focus areas
          </p>

          <div>
            <textarea
              value={description}
              onChange={(e) =>
                roleSkillStore.setCustomRoleDescription(e.target.value.slice(0, MAX_CHARS))
              }
              placeholder="I focus on application security, threat modeling, secure code review, and compliance frameworks (SOC2, ISO 27001). I work closely with the dev team to integrate security into the SDLC pipeline."
              className="w-full rounded-[10px] border border-border bg-background p-3 text-sm placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30 min-h-[160px] resize-y"
              maxLength={MAX_CHARS}
              aria-label="Describe your custom role"
              aria-describedby="custom-role-char-count"
              disabled={isGenerating}
            />
            <div
              id="custom-role-char-count"
              className="mt-1 text-right text-xs text-muted-foreground"
              aria-live="polite"
            >
              {charCount} / {MAX_CHARS} characters
            </div>
          </div>

          <p className="text-xs text-muted-foreground">
            Your role name will be auto-generated by AI from this description. You can edit it after
            generation.
          </p>

          {/* Min chars hint */}
          {charCount > 0 && charCount < MIN_CHARS && (
            <p className="text-xs text-muted-foreground">
              Min {MIN_CHARS} characters required ({MIN_CHARS - charCount} more)
            </p>
          )}

          {/* Generate button */}
          <div className="flex justify-start">
            <Button
              onClick={onGenerate}
              disabled={!canGenerate}
              aria-busy={isGenerating}
              className="bg-[#6B8FAD] hover:bg-[#5A7D9A] text-white"
            >
              <Sparkles className="mr-1.5 h-4 w-4" />
              {isGenerating ? 'Generating...' : 'Generate Skill'}
            </Button>
          </div>
        </div>

        {/* Right panel — Examples */}
        <div className="flex-[2] flex flex-col gap-3">
          <p className="text-sm font-medium">How Role Skills Work</p>
          <p className="text-xs text-muted-foreground">
            Each role changes how the AI assistant responds to your requests:
          </p>
          {CUSTOM_ROLE_EXAMPLES.map((ex) => (
            <div key={ex.roleName} className="rounded-lg border p-3 space-y-1">
              <p className="text-xs font-medium">{ex.roleName}</p>
              <p className="text-[10px] text-muted-foreground">{ex.description}</p>
              <div className="rounded bg-[#6B8FAD]/10 px-2 py-1.5">
                <p className="text-[10px] text-[#6B8FAD]">
                  <Sparkles className="inline h-2.5 w-2.5 mr-0.5" />
                  {ex.example}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
});
