"""Export/Import schemas for workspace data portability.

T357: Pydantic schemas for workspace data export/import with validation.
Excludes sensitive data (tokens, passwords, encrypted keys).
"""

from __future__ import annotations

from datetime import date, datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import Field

from pilot_space.api.v1.schemas.base import BaseSchema

# =============================================================================
# Export Schema Version
# =============================================================================

EXPORT_SCHEMA_VERSION = "1.0.0"


# =============================================================================
# Conflict Resolution Mode
# =============================================================================


class ConflictMode(StrEnum):
    """Conflict resolution strategy during import.

    Attributes:
        SKIP: Skip entities that already exist.
        OVERWRITE: Overwrite existing entities with imported data.
        FAIL: Abort import if any conflict detected.
    """

    SKIP = "skip"
    OVERWRITE = "overwrite"
    FAIL = "fail"


# =============================================================================
# Export Entity Schemas
# =============================================================================


class WorkspaceExport(BaseSchema):
    """Workspace data for export.

    Excludes: owner_id (remapped on import), integrations (contain secrets).
    """

    id: UUID = Field(description="Original workspace ID")
    name: str = Field(min_length=1, max_length=255)
    slug: str = Field(description="URL-friendly identifier")
    description: str | None = Field(default=None)
    settings: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    updated_at: datetime


class ProjectExport(BaseSchema):
    """Project data for export."""

    id: UUID
    workspace_id: UUID
    name: str = Field(min_length=1, max_length=255)
    identifier: str = Field(description="Project code (e.g., PS, AUTH)")
    description: str | None = None
    emoji: str | None = None
    cover_image_url: str | None = None
    settings: dict[str, Any] = Field(default_factory=dict)
    issue_counter: int = Field(default=0, ge=0)
    is_public: bool = False
    created_at: datetime
    updated_at: datetime


class StateExport(BaseSchema):
    """State data for export."""

    id: UUID
    project_id: UUID
    name: str = Field(min_length=1, max_length=50)
    description: str | None = None
    color: str = Field(pattern=r"^#[0-9A-Fa-f]{6}$")
    group: str = Field(description="State group: backlog|unstarted|started|completed|cancelled")
    sort_order: int = 0
    is_default: bool = False
    created_at: datetime


class LabelExport(BaseSchema):
    """Label data for export."""

    id: UUID
    workspace_id: UUID
    project_id: UUID | None = None
    name: str = Field(min_length=1, max_length=50)
    color: str = Field(pattern=r"^#[0-9A-Fa-f]{6}$")
    description: str | None = None
    parent_id: UUID | None = None
    created_at: datetime


class IssueExport(BaseSchema):
    """Issue data for export.

    Excludes: activities (audit log), integration_links (external refs).
    """

    id: UUID
    workspace_id: UUID
    project_id: UUID
    sequence_id: int = Field(ge=1)
    name: str = Field(min_length=1, max_length=255)
    description: str | None = None
    description_html: str | None = None
    state_id: UUID
    priority: str | None = Field(
        default=None,
        description="Priority: urgent|high|medium|low|none",
    )
    start_date: date | None = None
    target_date: date | None = None
    completed_at: datetime | None = None
    estimate_points: int | None = Field(default=None, ge=0)
    assignee_id: UUID | None = None
    reporter_id: UUID
    cycle_id: UUID | None = None
    module_id: UUID | None = None
    parent_id: UUID | None = None
    sort_order: int = 0
    label_ids: list[UUID] = Field(default_factory=list)
    ai_metadata: dict[str, Any] | None = None
    created_at: datetime
    updated_at: datetime


class NoteExport(BaseSchema):
    """Note data for export.

    Excludes: annotations, discussions (can be regenerated by AI).
    """

    id: UUID
    workspace_id: UUID
    project_id: UUID | None = None
    title: str = Field(min_length=1, max_length=255)
    content: dict[str, Any] = Field(default_factory=dict, description="TipTap JSON content")
    summary: str | None = None
    word_count: int = Field(default=0, ge=0)
    reading_time_mins: int = Field(default=0, ge=0)
    is_pinned: bool = False
    owner_id: UUID
    template_id: UUID | None = None
    created_at: datetime
    updated_at: datetime


class CycleExport(BaseSchema):
    """Cycle (sprint) data for export."""

    id: UUID
    workspace_id: UUID
    project_id: UUID
    name: str = Field(min_length=1, max_length=255)
    description: str | None = None
    start_date: date
    end_date: date
    status: str = Field(description="Status: draft|active|completed|cancelled")
    sequence: int = Field(ge=1)
    owned_by_id: UUID | None = None
    created_at: datetime
    updated_at: datetime


class ModuleExport(BaseSchema):
    """Module (epic) data for export."""

    id: UUID
    workspace_id: UUID
    project_id: UUID
    name: str = Field(min_length=1, max_length=255)
    description: str | None = None
    status: str = Field(description="Status: planned|active|completed|cancelled")
    target_date: date | None = None
    sort_order: int = 0
    lead_id: UUID | None = None
    created_at: datetime
    updated_at: datetime


class TemplateExport(BaseSchema):
    """Template data for export."""

    id: UUID
    workspace_id: UUID
    project_id: UUID | None = None
    name: str = Field(min_length=1, max_length=100)
    description: str | None = None
    emoji: str | None = None
    content: dict[str, Any] = Field(description="TipTap JSON content")
    template_type: str = Field(description="Type: note|page|issue_description")
    sort_order: int = 0
    created_at: datetime
    updated_at: datetime


# =============================================================================
# Complete Export Schema
# =============================================================================


class WorkspaceDataExport(BaseSchema):
    """Complete workspace export package.

    Contains all exportable entities with version metadata.
    """

    version: str = Field(default=EXPORT_SCHEMA_VERSION, description="Schema version")
    exported_at: datetime = Field(description="Export timestamp")
    exported_by: UUID | None = Field(default=None, description="User who initiated export")
    workspace: WorkspaceExport
    projects: list[ProjectExport] = Field(default_factory=list)
    issues: list[IssueExport] = Field(default_factory=list)
    notes: list[NoteExport] = Field(default_factory=list)
    cycles: list[CycleExport] = Field(default_factory=list)
    modules: list[ModuleExport] = Field(default_factory=list)
    labels: list[LabelExport] = Field(default_factory=list)
    states: list[StateExport] = Field(default_factory=list)
    templates: list[TemplateExport] = Field(default_factory=list)


# =============================================================================
# API Request/Response Schemas
# =============================================================================


class ExportJobRequest(BaseSchema):
    """Request to initiate workspace export."""

    include_issues: bool = Field(default=True, description="Include issues in export")
    include_notes: bool = Field(default=True, description="Include notes in export")
    include_cycles: bool = Field(default=True, description="Include cycles in export")
    include_modules: bool = Field(default=True, description="Include modules in export")


class ExportJobResponse(BaseSchema):
    """Response for export job initiation."""

    job_id: str = Field(description="Unique job identifier")
    status: str = Field(description="Job status: pending|processing|completed|failed")
    workspace_id: UUID
    estimated_size_bytes: int | None = Field(default=None, description="Estimated export size")
    message: str | None = None


class ExportJobStatus(BaseSchema):
    """Export job status response."""

    job_id: str
    status: str = Field(description="Job status: pending|processing|completed|failed")
    progress_percent: int = Field(default=0, ge=0, le=100)
    download_url: str | None = Field(default=None, description="URL to download export")
    expires_at: datetime | None = Field(default=None, description="Download URL expiration")
    error: str | None = Field(default=None, description="Error message if failed")
    entity_counts: dict[str, int] | None = Field(
        default=None,
        description="Count of entities exported",
    )


class ImportJobRequest(BaseSchema):
    """Request to initiate workspace import."""

    conflict_mode: ConflictMode = Field(
        default=ConflictMode.FAIL,
        description="How to handle existing entities",
    )
    dry_run: bool = Field(
        default=False,
        description="Validate without committing changes",
    )
    new_workspace_name: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="Name for new workspace (if creating)",
    )
    new_workspace_slug: str | None = Field(
        default=None,
        description="Slug for new workspace (if creating)",
    )


class ImportJobResponse(BaseSchema):
    """Response for import job initiation."""

    job_id: str = Field(description="Unique job identifier")
    status: str = Field(description="Job status: pending|processing|completed|failed")
    workspace_id: UUID | None = Field(default=None, description="Created/updated workspace ID")
    message: str | None = None


class ImportJobStatus(BaseSchema):
    """Import job status response."""

    job_id: str
    status: str = Field(description="Job status: pending|processing|completed|failed")
    progress_percent: int = Field(default=0, ge=0, le=100)
    workspace_id: UUID | None = None
    error: str | None = None
    entity_counts: dict[str, int] | None = Field(
        default=None,
        description="Count of entities imported",
    )
    skipped_counts: dict[str, int] | None = Field(
        default=None,
        description="Count of entities skipped",
    )
    validation_errors: list[str] | None = Field(
        default=None,
        description="Validation errors if dry_run",
    )


class ImportResult(BaseSchema):
    """Result from workspace import operation."""

    workspace_id: UUID
    entity_counts: dict[str, int] = Field(
        description="Count of entities imported by type",
    )
    skipped_count: int = Field(default=0, description="Total skipped entities")
    errors: list[str] = Field(default_factory=list, description="Non-fatal errors")


__all__ = [
    "EXPORT_SCHEMA_VERSION",
    "ConflictMode",
    "CycleExport",
    "ExportJobRequest",
    "ExportJobResponse",
    "ExportJobStatus",
    "ImportJobRequest",
    "ImportJobResponse",
    "ImportJobStatus",
    "ImportResult",
    "IssueExport",
    "LabelExport",
    "ModuleExport",
    "NoteExport",
    "ProjectExport",
    "StateExport",
    "TemplateExport",
    "WorkspaceDataExport",
    "WorkspaceExport",
]
