'use client';

/**
 * AIThreadIndicator - Collapsed AI conversation thread indicator
 *
 * Shows a collapsed summary of AI conversation threads attached to note blocks.
 * Follows UI Spec v3.3 and DD-013 Note-First workflow.
 *
 * @see DD-013 Note-First Collaborative Workspace
 * @see UI Spec v3.3 Section 7 - Note Canvas
 */
import { Sparkles, ChevronRight, FileText } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Badge } from '@/components/ui/badge';

export interface AIThreadArtifact {
  /** Artifact type (e.g., 'code', 'document', 'diagram') */
  type: string;
  /** Artifact name for display */
  name: string;
}

export interface AIThreadIndicatorProps {
  /** Number of messages in the AI thread */
  messageCount: number;
  /** Whether the thread is currently expanded */
  isExpanded?: boolean;
  /** Callback when user clicks to expand/collapse */
  onToggle?: () => void;
  /** Optional artifact generated by the AI thread */
  artifact?: AIThreadArtifact;
  /** Additional CSS classes */
  className?: string;
}

/**
 * AIThreadIndicator displays a collapsed view of AI conversation threads
 *
 * Visual design per UI Spec v3.3 / Prototype v4:
 * - Left border accent (3px) with AI color
 * - AI icon + "AI thread" label
 * - Message count badge
 * - Optional artifact preview
 * - Chevron for expand/collapse
 *
 * @example
 * ```tsx
 * <AIThreadIndicator
 *   messageCount={5}
 *   artifact={{ type: 'code', name: 'auth-service.ts' }}
 *   onToggle={() => setExpanded(!expanded)}
 * />
 * ```
 */
export function AIThreadIndicator({
  messageCount,
  isExpanded = false,
  onToggle,
  artifact,
  className,
}: AIThreadIndicatorProps) {
  // Don't render if there are no messages
  if (messageCount === 0) {
    return null;
  }

  return (
    <button
      type="button"
      onClick={onToggle}
      className={cn(
        // Base layout
        'flex items-center gap-2 w-full',
        'px-3 py-2 mt-2',
        // AI accent styling - DD-013 aligned
        'bg-ai-muted border-l-[3px] border-ai',
        'rounded-r-[10px]',
        // Interactive states
        'cursor-pointer transition-all duration-150',
        'hover:shadow-warm-sm hover:bg-ai-muted/80',
        'focus:outline-none focus-visible:ring-2 focus-visible:ring-ai focus-visible:ring-offset-2',
        className
      )}
      aria-expanded={isExpanded}
      aria-label={`AI thread with ${messageCount} messages${artifact ? `, artifact: ${artifact.name}` : ''}`}
    >
      {/* AI Icon */}
      <Sparkles className="h-4 w-4 text-ai shrink-0" aria-hidden="true" />

      {/* Thread Label */}
      <span className="text-sm font-medium text-ai">AI thread</span>

      {/* Message Count Badge */}
      <Badge
        variant="outline"
        className={cn('text-xs border-ai-border text-ai', 'bg-transparent hover:bg-transparent')}
      >
        {messageCount} {messageCount === 1 ? 'message' : 'messages'}
      </Badge>

      {/* Artifact Preview (optional) */}
      {artifact && (
        <div
          className={cn(
            'ml-auto flex items-center gap-1.5',
            'px-2 py-1',
            'bg-background rounded-sm',
            'text-xs text-muted-foreground'
          )}
        >
          <FileText className="h-3 w-3 shrink-0" aria-hidden="true" />
          <span className="truncate max-w-[120px]">{artifact.name}</span>
        </div>
      )}

      {/* Expand/Collapse Chevron */}
      <ChevronRight
        className={cn(
          'h-4 w-4 text-muted-foreground shrink-0 transition-transform duration-200',
          !artifact && 'ml-auto',
          isExpanded && 'rotate-90'
        )}
        aria-hidden="true"
      />
    </button>
  );
}

export default AIThreadIndicator;
