"""DiscussionComment SQLAlchemy model.

DiscussionComment represents individual comments within a ThreadedDiscussion.
Comments can be from users or AI-generated.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, ForeignKey, Index, Text, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from pilot_space.infrastructure.database.base import WorkspaceScopedModel

if TYPE_CHECKING:
    from pilot_space.infrastructure.database.models.threaded_discussion import (
        ThreadedDiscussion,
    )
    from pilot_space.infrastructure.database.models.user import User


class DiscussionComment(WorkspaceScopedModel):
    """DiscussionComment model for comments within a discussion thread.

    Comments are individual messages in a discussion thread.
    They can be user-authored or AI-generated.

    Attributes:
        discussion_id: FK to parent ThreadedDiscussion.
        author_id: FK to User who authored the comment.
        content: The comment text content.
        is_ai_generated: Whether this comment was generated by AI.
    """

    __tablename__ = "discussion_comments"  # type: ignore[assignment]

    # Parent discussion reference
    discussion_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("threaded_discussions.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Author reference
    author_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Comment content
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # AI generation flag
    is_ai_generated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
    )

    # Relationships
    discussion: Mapped[ThreadedDiscussion] = relationship(
        "ThreadedDiscussion",
        back_populates="comments",
        lazy="joined",
    )
    author: Mapped[User] = relationship(
        "User",
        foreign_keys=[author_id],
        lazy="joined",
    )

    # Indexes and constraints
    __table_args__ = (
        Index("ix_discussion_comments_discussion_id", "discussion_id"),
        Index("ix_discussion_comments_author_id", "author_id"),
        Index("ix_discussion_comments_is_ai_generated", "is_ai_generated"),
        Index("ix_discussion_comments_is_deleted", "is_deleted"),
        Index("ix_discussion_comments_created_at", "created_at"),
    )

    def __repr__(self) -> str:
        """Return string representation."""
        content_preview = self.content[:50] if self.content else ""
        ai_tag = " [AI]" if self.is_ai_generated else ""
        return f"<DiscussionComment(id={self.id}{ai_tag}, content={content_preview}...)>"
