'use client';

/**
 * SkillPreviewCard — Rendered in assistant messages after skill generation.
 * Shows skill name, tags, usage, word count. Actions: Preview, Save, Regenerate.
 *
 * "Preview" dispatches `pilot:preview-skill` → useSkillPreview opens FilePreviewModal.
 * "Save & Activate" persists via useCreateUserSkill.
 * "Regenerate" re-calls generate API with same description.
 */

import { memo, useState, useCallback } from 'react';
import { Eye, Save, RefreshCw, Loader2, Sparkles, Check } from 'lucide-react';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { useCreateUserSkill } from '@/services/api/user-skills';
import { useGenerateSkill } from '@/features/onboarding/hooks/useRoleSkillActions';
import type { GenerateSkillResponse } from '@/services/api/role-skills';
import type { SkillPreviewDetail } from '../hooks/useSkillPreview';

export interface SkillPreviewCardProps {
  /** Generated skill data from the API */
  generatedSkill: GenerateSkillResponse;
  /** Experience description used for generation (for regeneration) */
  experienceDescription: string;
  /** Workspace ID for API calls */
  workspaceId: string;
  /** Called when skill data is updated (after regeneration) */
  onSkillUpdated?: (skill: GenerateSkillResponse) => void;
  className?: string;
}

export const SkillPreviewCard = memo<SkillPreviewCardProps>(
  ({ generatedSkill, experienceDescription, workspaceId, onSkillUpdated, className }) => {
    const [saved, setSaved] = useState(false);
    const createSkill = useCreateUserSkill(workspaceId);
    const generateSkill = useGenerateSkill({ workspaceId });

    const handlePreview = useCallback(() => {
      const detail: SkillPreviewDetail = {
        skillContent: generatedSkill.skillContent,
        skillName: generatedSkill.suggestedRoleName,
      };
      window.dispatchEvent(new CustomEvent('pilot:preview-skill', { detail }));
    }, [generatedSkill]);

    const handleSave = useCallback(async () => {
      try {
        await createSkill.mutateAsync({
          skill_content: generatedSkill.skillContent,
          skill_name: generatedSkill.suggestedRoleName,
          experience_description: experienceDescription,
          tags: generatedSkill.suggestedTags,
          usage: generatedSkill.suggestedUsage ?? undefined,
        });
        setSaved(true);
        toast.success('Skill saved and active');
      } catch {
        toast.error('Failed to save skill');
      }
    }, [createSkill, generatedSkill, experienceDescription]);

    const handleRegenerate = useCallback(async () => {
      try {
        const result = await generateSkill.mutateAsync({
          roleType: 'custom',
          experienceDescription,
        });
        onSkillUpdated?.(result);
        toast.success('Skill regenerated');
      } catch {
        // Error toast handled by useGenerateSkill onError
      }
    }, [generateSkill, experienceDescription, onSkillUpdated]);

    const wordCount = generatedSkill.wordCount;

    return (
      <div className={className} role="region" aria-label="Generated skill preview">
        {/* Header */}
        <div className="flex items-center gap-2 mb-3">
          <Sparkles className="h-4 w-4 text-[var(--ai)]" />
          <span className="text-sm font-medium">Generated Skill</span>
          <span className="text-xs text-muted-foreground ml-auto">
            {wordCount} word{wordCount !== 1 ? 's' : ''}
          </span>
        </div>

        {/* Skill name */}
        <h4 className="text-sm font-semibold mb-2">{generatedSkill.suggestedRoleName}</h4>

        {/* Usage */}
        {generatedSkill.suggestedUsage && (
          <p className="text-xs text-muted-foreground mb-3 line-clamp-2">
            {generatedSkill.suggestedUsage}
          </p>
        )}

        {/* Tags */}
        {generatedSkill.suggestedTags.length > 0 && (
          <div className="flex flex-wrap gap-1 mb-3">
            {generatedSkill.suggestedTags.map((tag) => (
              <span
                key={tag}
                className="inline-flex items-center rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground"
              >
                {tag}
              </span>
            ))}
          </div>
        )}

        {/* Model info */}
        <div className="text-[10px] text-muted-foreground/60 mb-3">
          Generated by {generatedSkill.generationModel} in{' '}
          {(generatedSkill.generationTimeMs / 1000).toFixed(1)}s
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" className="gap-1.5 text-xs h-7" onClick={handlePreview}>
            <Eye className="h-3 w-3" />
            Preview
          </Button>

          <Button
            size="sm"
            className={cn(
              'gap-1.5 text-xs h-7',
              saved
                ? 'bg-green-600 hover:bg-green-600 text-white'
                : 'bg-[var(--ai)] hover:bg-[var(--ai)]/90 text-white'
            )}
            onClick={handleSave}
            disabled={saved || createSkill.isPending}
          >
            {createSkill.isPending ? (
              <Loader2 className="h-3 w-3 animate-spin" />
            ) : saved ? (
              <Check className="h-3 w-3" />
            ) : (
              <Save className="h-3 w-3" />
            )}
            {saved ? 'Saved' : createSkill.isPending ? 'Saving...' : 'Save & Activate'}
          </Button>

          <Button
            variant="ghost"
            size="sm"
            className="gap-1.5 text-xs h-7 text-muted-foreground"
            onClick={handleRegenerate}
            disabled={generateSkill.isPending || saved}
          >
            {generateSkill.isPending ? (
              <Loader2 className="h-3 w-3 animate-spin" />
            ) : (
              <RefreshCw className="h-3 w-3" />
            )}
            Regenerate
          </Button>
        </div>
      </div>
    );
  }
);

SkillPreviewCard.displayName = 'SkillPreviewCard';
